from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    FirebaseLoginView,
    EssaySubmissionView,
    EssayListView,
    EssayDetailView,
    ReadingTestListView,
    ReadingTestDetailView,
    StartWritingSessionView,
    SubmitTaskView,
    FinishWritingSessionView,
    WritingPromptViewSet,
    AdminEssayListView,
    StartReadingTestView,
    SubmitReadingTestView,
    ReadingTestSessionListView,
    ReadingTestSessionDetailView,
    ReadingTestCreateView,
    ReadingQuestionAddView,
    ActivateReadingTestView,
    ReadingTestUpdateDeleteView,
    ReadingQuestionUpdateDeleteView,
    AdminReadingSessionListView,
    AdminReadingSessionDetailView,
    ListeningTestListView,
    ListeningTestDetailView,
    StartListeningTestView,
    SubmitListeningTestView,
    ListeningTestSessionListView,
    ListeningTestSessionDetailView,
    ListeningTestCreateView,
    ListeningQuestionAddView,
    ActivateListeningTestView,
    ListeningTestUpdateDeleteView,
    ListeningQuestionUpdateDeleteView,
    AdminListeningSessionListView,
    AdminListeningSessionDetailView
)

router = DefaultRouter()
router.register(r'prompts', WritingPromptViewSet, basename='prompt')

urlpatterns = router.urls + [
    path('login/', FirebaseLoginView.as_view(), name='firebase-login'),
    path('essay/', EssaySubmissionView.as_view(), name='essay-submit'),
    path('essays/', EssayListView.as_view(), name='essay-list'),
    path('essays/<int:pk>/', EssayDetailView.as_view(), name='essay-detail'),
    path('reading/tests/', ReadingTestListView.as_view(), name='reading-test-list'),
    path('reading/tests/create/', ReadingTestCreateView.as_view(), name='reading-test-create'),
    path('reading/tests/<int:test_id>/questions/add/', ReadingQuestionAddView.as_view(), name='reading-question-add'),
    path('reading/tests/<int:pk>/', ReadingTestDetailView.as_view(), name='reading-test-detail'),
    path('reading/tests/<int:pk>/start/', StartReadingTestView.as_view(), name='reading-test-start'),
    path('reading/tests/<int:pk>/activate/', ActivateReadingTestView.as_view(), name='reading-test-activate'),
    path('reading/tests/<int:pk>/update/', ReadingTestUpdateDeleteView.as_view(), name='reading-test-update-delete'),
    path('reading/sessions/<int:session_id>/submit/', SubmitReadingTestView.as_view(), name='reading-test-submit'),
    path('reading/sessions/', ReadingTestSessionListView.as_view(), name='reading-session-list'),
    path('reading/sessions/<int:pk>/', ReadingTestSessionDetailView.as_view(), name='reading-session-detail'),
    path('start-writing-session/', StartWritingSessionView.as_view(), name='start-writing-session'),
    path('submit-task/', SubmitTaskView.as_view(), name='submit-task'),
    path('finish-writing-session/', FinishWritingSessionView.as_view(), name='finish-writing-session'),
    path('admin/essays/', AdminEssayListView.as_view(), name='admin-essay-list'),
    path('admin/reading-sessions/', AdminReadingSessionListView.as_view(), name='admin-reading-session-list'),
    path('admin/reading-sessions/<int:pk>/', AdminReadingSessionDetailView.as_view(), name='admin-reading-session-detail'),
    path('admin/reading/create/', ReadingTestCreateView.as_view(), name='reading-test-create'),
    path('admin/reading/<int:test_id>/questions/add/', ReadingQuestionAddView.as_view(), name='reading-question-add'),
    path('admin/reading/<int:pk>/activate/', ActivateReadingTestView.as_view(), name='reading-test-activate'),
    path('admin/reading/<int:pk>/', ReadingTestUpdateDeleteView.as_view(), name='reading-test-update-delete'),
    path('reading/questions/<int:pk>/', ReadingQuestionUpdateDeleteView.as_view(), name='reading-question-update-delete'),
    
    # Listening URLs
    path('listening/tests/', ListeningTestListView.as_view(), name='listening-test-list'),
    path('listening/tests/create/', ListeningTestCreateView.as_view(), name='listening-test-create'),
    path('listening/tests/<int:test_id>/questions/add/', ListeningQuestionAddView.as_view(), name='listening-question-add'),
    path('listening/tests/<int:pk>/', ListeningTestDetailView.as_view(), name='listening-test-detail'),
    path('listening/tests/<int:pk>/start/', StartListeningTestView.as_view(), name='listening-test-start'),
    path('listening/tests/<int:pk>/activate/', ActivateListeningTestView.as_view(), name='listening-test-activate'),
    path('listening/tests/<int:pk>/update/', ListeningTestUpdateDeleteView.as_view(), name='listening-test-update-delete'),
    path('listening/sessions/<int:session_id>/submit/', SubmitListeningTestView.as_view(), name='listening-test-submit'),
    path('listening/sessions/', ListeningTestSessionListView.as_view(), name='listening-session-list'),
    path('listening/sessions/<int:pk>/', ListeningTestSessionDetailView.as_view(), name='listening-session-detail'),
    path('admin/listening-sessions/', AdminListeningSessionListView.as_view(), name='admin-listening-session-list'),
    path('admin/listening-sessions/<int:pk>/', AdminListeningSessionDetailView.as_view(), name='admin-listening-session-detail'),
    path('admin/listening/create/', ListeningTestCreateView.as_view(), name='listening-test-create'),
    path('admin/listening/<int:test_id>/questions/add/', ListeningQuestionAddView.as_view(), name='listening-question-add'),
    path('admin/listening/<int:pk>/activate/', ActivateListeningTestView.as_view(), name='listening-test-activate'),
    path('admin/listening/<int:pk>/', ListeningTestUpdateDeleteView.as_view(), name='listening-test-update-delete'),
    path('listening/questions/<int:pk>/', ListeningQuestionUpdateDeleteView.as_view(), name='listening-question-update-delete'),
]
