# Generated by Django 4.2.21 on 2025-05-31 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=10)),
                ('question_text', models.TextField()),
                ('submitted_text', models.TextField()),
                ('score_task', models.FloatField(null=True)),
                ('score_coherence', models.FloatField(null=True)),
                ('score_lexical', models.FloatField(null=True)),
                ('score_grammar', models.FloatField(null=True)),
                ('overall_band', models.FloatField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
