# Generated by Django 4.2.21 on 2025-06-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingprompt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='writing_images/'),
        ),
        migrations.AddField(
            model_name='writingprompt',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
