# Generated by Django 5.1.3 on 2025-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_readingpassage_readingtestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
