# Generated by Django 5.1.3 on 2025-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_readingtest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reading_images/'),
        ),
    ]
